# https://aka.ms/yaml


jobs:
  - job: 'Build_Windows_HTTP'
    pool:
      vmImage: 'vs2017-win2016'

    steps:
      - script: git submodule update --init --recursive
        displayName: 'Checkout Submodules'

      - task: DownloadPipelineArtifact@2
        inputs:
          project: '4b438742-da7e-4123-8cf4-55564485db7e'
          pipelineId: '329'

          buildType: 'specific'
          #definition: '8'
          buildVersionToDownload: 'latestFromBranch'
          #branchName: "refs/heads/windows_obs"
          artifactName: obs_deps_windows
          targetPath: $(Build.SourcesDirectory)/CI/obs_deps/

      - script: $(Build.SourcesDirectory)\CI\install-script-win.cmd
        displayName: 'Setup, CMake'
        workingDirectory: $(Build.SourcesDirectory)\CI
        env:
          GOOGLE_API_KEY: $(GOOGLE_API_KEY)

      - task: MSBuild@1
        displayName: 'Build 64-bit'
        inputs:
          msbuildArguments: '/m /p:Configuration=RelWithDebInfo'
          solution: $(Build.SourcesDirectory)\CI\build_64\obs_google_caption_plugin.sln

      - task: MSBuild@1
        displayName: 'Build 32-bit'
        inputs:
          msbuildArguments: '/m /p:Configuration=RelWithDebInfo'
          solution: $(Build.SourcesDirectory)\CI\build_32\obs_google_caption_plugin.sln

      - script: $(Build.SourcesDirectory)\CI\post-install-script-win.cmd
        workingDirectory: $(Build.SourcesDirectory)\CI
        displayName: 'Post install'

      - task: PublishPipelineArtifact@1
        inputs:
          path: '$(Build.SourcesDirectory)/CI/release_dir/'
          artifact: Closed_Captions_Plugin__Release_Windows_HTTP


